export const selectors = {
    logInButtonOnLandingPage: '[aria-label="Login page button"]',
    LoginEmailInput: '[aria-label="Login Email input field"]',
    LoginPasswordInput: '[aria-label="Login Password input field"]',
    LoginButton: '[aria-label="Login button"]',
    DashboardNavigateStarButton: '[data-testid="StarRoundedIcon"]',
    DashboardHeader: '[aria-label="Dashboard Header"]',
    ProfileHeaderFullName: '[aria-label="Profile Header Full Name"]',
    ProfileHeaderMajors: '[aria-label="Profile Header Majors"]',
    ProfileHeaderGraduationYear: '[aria-label="Profile Header Graduation Year"]',
    ProfileHeaderLocation: '[aria-label="Profile Header Location"]',
    ProfileAlertPending: '[aria-label="Profile Alert Pending"]',
    ProfileAbout: '[aria-label="Profile About"]',
    ProfileWorkExperience: '[aria-label="Profile Work Experience"]',
    ProfileVolunteerExperience: '[aria-label="Profile Volunteer Experience"]',
    ProfileKeywords: '[aria-label="Profile Keywords"]',
    ProfileDeactivateAccount: '[aria-label="Profile Deactivate Account"]',
}