export const selectors = {
    logInButtonOnLandingPage: '[aria-label="Login page button"]',
    LoginEmailInput: '[aria-label="Login Email input field"]',
    LoginPasswordInput: '[aria-label="Login Password input field"]',
    LoginButton: '[aria-label="Login button"]',
    DashboardNavigateStarButton: '[data-testid="StarRoundedIcon"]',
    DashboardHeader: '[aria-label="Dashboard Header"]',
    DashboardHeaderCount: '[aria-label="Dashboard Header Count"]',
    DashboardUpcoming: '[aria-label="Dashboard Upcoming Section"]',
    DashboardPendingTitle: '[aria-label="Dashboard Pending Title"]',
    DashboardPendingDropdown: '[aria-label="Dashboard Pending Dropdown"]',
    DashboardBrowseButton: '[aria-label="Dashboard Browse Button"]',
    DashboardCreateButton: '[aria-label="Dashboard Create Button"]',
    ProfileHeaderFullName: '[aria-label="Profile Header Full Name"]',
    ProfileHeaderMajors: '[aria-label="Profile Header Majors"]',
    ProfileHeaderGraduationYear: '[aria-label="Profile Header Graduation Year"]',
    ProfileHeaderLocation: '[aria-label="Profile Header Location"]',
    ProfileAlertPending: '[aria-label="Profile Alert Pending"]',
    ProfileAbout: '[aria-label="Profile About"]',
    ProfileWorkExperience: '[aria-label="Profile Work Experience"]',
    ProfileVolunteerExperience: '[aria-label="Profile Volunteer Experience"]',
    ProfileKeywords: '[aria-label="Profile Keywords"]',
    ProfileDeactivateAccount: '[aria-label="Profile Deactivate Account"]',
    ViewOpportunityTitle: '[aria-label="Page Header Title"]',
    ViewOpportunityHost: '[aria-label="Page Header Host"]',
    ViewOpportunityStartDate: '[aria-label="Page Header Start Date"]',
    ViewOpportunityEndDate: '[aria-label="Page Header End Date"]',
    ViewOpportunityDuration: '[aria-label="Page Header Duration"]',
    ViewOpportunityLocationType: '[aria-label="Page Header Location Type"]',
    ViewOpportunityLocation: '[aria-label="Page Header Location"]',
    ViewOpportunityMembers: '[aria-label="View Opportunity Members"]',
    ViewOpportunityDescription: '[aria-label="View Opportunity Description"]',
    ViewOpportunityRoles: '[aria-label="View Opportunity Roles"]',
    ViewOpportunityKeywords: '[aria-label="View Opportunity Keywords"]',

    
}